# YaST2: modules testsuite
#
# Description:
#   Main file for all tests
#
# Author:
#   Michal Svec <msvec@suse.cz>
#
# $Id: testsuite.exp 60074 2009-12-11 15:09:27Z aschnell $

global CASE
# there must be a space before the closing brace!
if [catch {set pattern $CASE }] {
    # CASE undefined, do a glob
    set pattern "*"
}

set filenames [lsort [glob "$srcdir/tests/$pattern.ycp"]]

puts "\nChecking started\n"

foreach file $filenames { testsuite-run $file }

puts "\nChecking finished\n"
