#!/bin/bash
/usr/lib/YaST2/bin/y2base /usr/share/YaST2/clients/create_udev_cdrom.ycp ncurses
FILES=`hwinfo --cdrom 2>/dev/null | grep "SysFS ID:" | \
       sed -e "s:^[^/]*::" -e "s:^:/sys:" -e "s:$:/uevent:"`
if [ -n "$FILES" ]
then
    for i in $FILES
    do
	echo add > $FILES
    done
fi
